
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTIVE ADDRESS ASSIGN BUY CANCEL CANCELED COLON COMMA COMPLETED DATE DISHTYPE ELSE EMAIL EQUIPMENT FLOAT GET HCID HOUR ID IF MEAL NIF NUMBER PASSWORD REGISTER RENT RESERVATIONS RESOURCES RESOURCE_TYPE SENSORTYPE STRING THEN UPDATE USER USERTYPE WEEKDAYstatement : ID ASSIGN valuestatement : instructionvalue : NUMBER\n| FLOAT\n| DATE\n| HOUR\n| WEEKDAY\n| DISHTYPE\n| SENSORTYPE\n| IDnumber_or_var : NUMBER \n| IDfloat_or_var : FLOAT \n| NUMBER \n| IDdate_or_var : DATE \n| IDhour_or_var : HOUR\n| IDdishtype_or_var : DISHTYPE\n| IDsensortype_or_var : SENSORTYPE \n| IDinstruction : RENT EQUIPMENT COLON number_or_var COMMA hour_or_var COMMA hour_or_var COMMA date_or_varreservation_status : ACTIVE\n| COMPLETED\n| CANCELEDinstruction : GET RESERVATIONSinstruction : GET RESERVATIONS number_or_varinstruction : UPDATE RESERVATIONS  number_or_var reservation_statusinstruction : CANCEL EQUIPMENT COLON number_or_varinstruction : BUY MEAL COLON dishtype_or_var COMMA date_or_varinstruction : CANCEL MEAL COLON number_or_varinstruction : REGISTER USER COLON STRING COMMA STRING COMMA NIF COMMA EMAIL COMMA ID COMMA PASSWORD COMMA USERTYPEinstruction : REGISTER EQUIPMENT COLON ID COMMA number_or_var COMMA number_or_var COMMA number_or_var COMMA number_or_var\n| REGISTER EQUIPMENT COLON HCIDinstruction : GET RESOURCESinstruction : GET RESOURCES number_or_varinstruction : GET RESOURCES EQUIPMENTinstruction : REGISTER EQUIPMENT COLON sensortype_or_var COMMA number_or_var COMMA float_or_varaction : RENT \n| BUY \n| REGISTER \n| CANCEL'
    
_lr_action_items = {'ID':([0,10,12,13,14,29,36,37,38,40,56,57,59,60,70,72,73,81,83,87,88,],[2,20,32,32,32,32,32,32,50,52,63,66,32,32,63,32,80,66,32,89,32,]),'RENT':([0,],[4,]),'GET':([0,],[5,]),'UPDATE':([0,],[6,]),'CANCEL':([0,],[7,]),'BUY':([0,],[8,]),'REGISTER':([0,],[9,]),'$end':([1,3,12,13,20,21,22,23,24,25,26,27,28,30,31,32,33,34,42,43,44,45,46,47,53,64,65,66,77,78,79,80,84,90,94,],[0,-2,-28,-37,-10,-1,-3,-4,-5,-6,-7,-8,-9,-29,-11,-12,-38,-39,-30,-25,-26,-27,-31,-33,-36,-32,-16,-17,-40,-13,-14,-15,-24,-35,-34,]),'ASSIGN':([2,],[10,]),'EQUIPMENT':([4,7,9,13,],[11,15,19,34,]),'RESERVATIONS':([5,6,],[12,14,]),'RESOURCES':([5,],[13,]),'MEAL':([7,8,],[16,17,]),'USER':([9,],[18,]),'NUMBER':([10,12,13,14,29,36,37,59,60,72,73,83,88,],[22,31,31,31,31,31,31,31,31,31,79,31,31,]),'FLOAT':([10,73,],[23,78,]),'DATE':([10,57,81,],[24,65,65,]),'HOUR':([10,56,70,],[25,62,62,]),'WEEKDAY':([10,],[26,]),'DISHTYPE':([10,38,],[27,49,]),'SENSORTYPE':([10,40,],[28,55,]),'COLON':([11,15,16,17,18,19,],[29,36,37,38,39,40,]),'ACTIVE':([31,32,35,],[-11,-12,43,]),'COMPLETED':([31,32,35,],[-11,-12,44,]),'CANCELED':([31,32,35,],[-11,-12,45,]),'COMMA':([31,32,41,48,49,50,51,52,54,55,61,62,63,67,68,69,74,75,76,85,86,89,92,],[-11,-12,56,57,-20,-21,58,59,60,-22,70,-18,-19,71,72,73,81,82,83,87,88,91,93,]),'STRING':([39,58,],[51,67,]),'HCID':([40,],[53,]),'NIF':([71,],[75,]),'EMAIL':([82,],[85,]),'PASSWORD':([91,],[92,]),'USERTYPE':([93,],[94,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'instruction':([0,],[3,]),'value':([10,],[21,]),'number_or_var':([12,13,14,29,36,37,59,60,72,83,88,],[30,33,35,41,46,47,68,69,76,86,90,]),'reservation_status':([35,],[42,]),'dishtype_or_var':([38,],[48,]),'sensortype_or_var':([40,],[54,]),'hour_or_var':([56,70,],[61,74,]),'date_or_var':([57,81,],[64,84,]),'float_or_var':([73,],[77,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID ASSIGN value','statement',3,'p_statement_assign','lss.py',319),
  ('statement -> instruction','statement',1,'p_statement_instruction','lss.py',325),
  ('value -> NUMBER','value',1,'p_value','lss.py',329),
  ('value -> FLOAT','value',1,'p_value','lss.py',330),
  ('value -> DATE','value',1,'p_value','lss.py',331),
  ('value -> HOUR','value',1,'p_value','lss.py',332),
  ('value -> WEEKDAY','value',1,'p_value','lss.py',333),
  ('value -> DISHTYPE','value',1,'p_value','lss.py',334),
  ('value -> SENSORTYPE','value',1,'p_value','lss.py',335),
  ('value -> ID','value',1,'p_value','lss.py',336),
  ('number_or_var -> NUMBER','number_or_var',1,'p_number_or_var','lss.py',341),
  ('number_or_var -> ID','number_or_var',1,'p_number_or_var','lss.py',342),
  ('float_or_var -> FLOAT','float_or_var',1,'p_float_or_var','lss.py',346),
  ('float_or_var -> NUMBER','float_or_var',1,'p_float_or_var','lss.py',347),
  ('float_or_var -> ID','float_or_var',1,'p_float_or_var','lss.py',348),
  ('date_or_var -> DATE','date_or_var',1,'p_date_or_var','lss.py',352),
  ('date_or_var -> ID','date_or_var',1,'p_date_or_var','lss.py',353),
  ('hour_or_var -> HOUR','hour_or_var',1,'p_hour_or_var','lss.py',357),
  ('hour_or_var -> ID','hour_or_var',1,'p_hour_or_var','lss.py',358),
  ('dishtype_or_var -> DISHTYPE','dishtype_or_var',1,'p_dishtype_or_var','lss.py',362),
  ('dishtype_or_var -> ID','dishtype_or_var',1,'p_dishtype_or_var','lss.py',363),
  ('sensortype_or_var -> SENSORTYPE','sensortype_or_var',1,'p_sensortype_or_var','lss.py',367),
  ('sensortype_or_var -> ID','sensortype_or_var',1,'p_sensortype_or_var','lss.py',368),
  ('instruction -> RENT EQUIPMENT COLON number_or_var COMMA hour_or_var COMMA hour_or_var COMMA date_or_var','instruction',10,'p_instruction_rent_resource','lss.py',373),
  ('reservation_status -> ACTIVE','reservation_status',1,'p_reservation_status','lss.py',402),
  ('reservation_status -> COMPLETED','reservation_status',1,'p_reservation_status','lss.py',403),
  ('reservation_status -> CANCELED','reservation_status',1,'p_reservation_status','lss.py',404),
  ('instruction -> GET RESERVATIONS','instruction',2,'p_instruction_get_reservations','lss.py',414),
  ('instruction -> GET RESERVATIONS number_or_var','instruction',3,'p_instruction_get_reservations_by_user','lss.py',426),
  ('instruction -> UPDATE RESERVATIONS number_or_var reservation_status','instruction',4,'p_instruction_update_reservation','lss.py',438),
  ('instruction -> CANCEL EQUIPMENT COLON number_or_var','instruction',4,'p_instruction_cancel_resource','lss.py',455),
  ('instruction -> BUY MEAL COLON dishtype_or_var COMMA date_or_var','instruction',6,'p_instruction_buy_meal','lss.py',469),
  ('instruction -> CANCEL MEAL COLON number_or_var','instruction',4,'p_instruction_cancel_meal','lss.py',479),
  ('instruction -> REGISTER USER COLON STRING COMMA STRING COMMA NIF COMMA EMAIL COMMA ID COMMA PASSWORD COMMA USERTYPE','instruction',16,'p_instruction_register_user','lss.py',487),
  ('instruction -> REGISTER EQUIPMENT COLON ID COMMA number_or_var COMMA number_or_var COMMA number_or_var COMMA number_or_var','instruction',12,'p_instruction_register_resource','lss.py',506),
  ('instruction -> REGISTER EQUIPMENT COLON HCID','instruction',4,'p_instruction_register_resource','lss.py',507),
  ('instruction -> GET RESOURCES','instruction',2,'p_instruction_get_resources','lss.py',543),
  ('instruction -> GET RESOURCES number_or_var','instruction',3,'p_instruction_get_resources_by_floor','lss.py',555),
  ('instruction -> GET RESOURCES EQUIPMENT','instruction',3,'p_instruction_get_resources_by_type','lss.py',568),
  ('instruction -> REGISTER EQUIPMENT COLON sensortype_or_var COMMA number_or_var COMMA float_or_var','instruction',8,'p_instruction_register_sensor','lss.py',591),
  ('action -> RENT','action',1,'p_action','lss.py',602),
  ('action -> BUY','action',1,'p_action','lss.py',603),
  ('action -> REGISTER','action',1,'p_action','lss.py',604),
  ('action -> CANCEL','action',1,'p_action','lss.py',605),
]
