
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESS ASSIGN BUY CANCEL COLON COMMA DATE DISHTYPE ELSE EMAIL EQUIPMENT FLOAT HOUR ID IF MEAL NIF NUMBER PASSWORD REGISTER RENT SENSORTYPE STRING THEN USER USERTYPE WEEKDAYstatement : ID ASSIGN valuestatement : instructionvalue : NUMBER\n| FLOAT\n| DATE\n| HOUR\n| WEEKDAY\n| DISHTYPE\n| SENSORTYPE\n| IDnumber_or_var : NUMBER \n| IDfloat_or_var : FLOAT \n| NUMBER \n| IDdate_or_var : DATE \n| IDhour_or_var : HOUR\n| IDdishtype_or_var : DISHTYPE\n| IDsensortype_or_var : SENSORTYPE \n| IDinstruction : RENT EQUIPMENT COLON number_or_var COMMA hour_or_var COMMA hour_or_var COMMA date_or_varinstruction : CANCEL EQUIPMENT COLON number_or_varinstruction : BUY MEAL COLON dishtype_or_var COMMA date_or_varinstruction : CANCEL MEAL COLON number_or_varinstruction : REGISTER USER COLON STRING COMMA STRING COMMA NIF COMMA EMAIL COMMA ID COMMA PASSWORD COMMA USERTYPEinstruction : REGISTER EQUIPMENT COLON ID COMMA number_or_varinstruction : REGISTER EQUIPMENT COLON sensortype_or_var COMMA number_or_var COMMA float_or_varaction : RENT \n| BUY \n| REGISTER \n| CANCEL'
    
_lr_action_items = {'ID':([0,8,24,25,26,27,29,42,43,45,46,56,58,65,69,],[2,15,32,32,32,37,39,49,52,32,32,49,64,52,70,]),'RENT':([0,],[4,]),'CANCEL':([0,],[5,]),'BUY':([0,],[6,]),'REGISTER':([0,],[7,]),'$end':([1,3,15,16,17,18,19,20,21,22,23,31,32,33,34,50,51,52,54,61,62,63,64,67,74,],[0,-2,-10,-1,-3,-4,-5,-6,-7,-8,-9,-11,-12,-25,-27,-26,-16,-17,-29,-30,-13,-14,-15,-24,-28,]),'ASSIGN':([2,],[8,]),'EQUIPMENT':([4,5,7,],[9,10,14,]),'MEAL':([5,6,],[11,12,]),'USER':([7,],[13,]),'NUMBER':([8,24,25,26,45,46,58,],[17,31,31,31,31,31,63,]),'FLOAT':([8,58,],[18,62,]),'DATE':([8,43,65,],[19,51,51,]),'HOUR':([8,42,56,],[20,48,48,]),'WEEKDAY':([8,],[21,]),'DISHTYPE':([8,27,],[22,36,]),'SENSORTYPE':([8,29,],[23,41,]),'COLON':([9,10,11,12,13,14,],[24,25,26,27,28,29,]),'STRING':([28,44,],[38,53,]),'COMMA':([30,31,32,35,36,37,38,39,40,41,47,48,49,53,55,59,60,68,70,72,],[42,-11,-12,43,-20,-21,44,45,46,-22,56,-18,-19,57,58,65,66,69,71,73,]),'NIF':([57,],[60,]),'EMAIL':([66,],[68,]),'PASSWORD':([71,],[72,]),'USERTYPE':([73,],[74,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'instruction':([0,],[3,]),'value':([8,],[16,]),'number_or_var':([24,25,26,45,46,],[30,33,34,54,55,]),'dishtype_or_var':([27,],[35,]),'sensortype_or_var':([29,],[40,]),'hour_or_var':([42,56,],[47,59,]),'date_or_var':([43,65,],[50,67,]),'float_or_var':([58,],[61,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID ASSIGN value','statement',3,'p_statement_assign','lss.py',207),
  ('statement -> instruction','statement',1,'p_statement_instruction','lss.py',213),
  ('value -> NUMBER','value',1,'p_value','lss.py',217),
  ('value -> FLOAT','value',1,'p_value','lss.py',218),
  ('value -> DATE','value',1,'p_value','lss.py',219),
  ('value -> HOUR','value',1,'p_value','lss.py',220),
  ('value -> WEEKDAY','value',1,'p_value','lss.py',221),
  ('value -> DISHTYPE','value',1,'p_value','lss.py',222),
  ('value -> SENSORTYPE','value',1,'p_value','lss.py',223),
  ('value -> ID','value',1,'p_value','lss.py',224),
  ('number_or_var -> NUMBER','number_or_var',1,'p_number_or_var','lss.py',229),
  ('number_or_var -> ID','number_or_var',1,'p_number_or_var','lss.py',230),
  ('float_or_var -> FLOAT','float_or_var',1,'p_float_or_var','lss.py',234),
  ('float_or_var -> NUMBER','float_or_var',1,'p_float_or_var','lss.py',235),
  ('float_or_var -> ID','float_or_var',1,'p_float_or_var','lss.py',236),
  ('date_or_var -> DATE','date_or_var',1,'p_date_or_var','lss.py',240),
  ('date_or_var -> ID','date_or_var',1,'p_date_or_var','lss.py',241),
  ('hour_or_var -> HOUR','hour_or_var',1,'p_hour_or_var','lss.py',245),
  ('hour_or_var -> ID','hour_or_var',1,'p_hour_or_var','lss.py',246),
  ('dishtype_or_var -> DISHTYPE','dishtype_or_var',1,'p_dishtype_or_var','lss.py',250),
  ('dishtype_or_var -> ID','dishtype_or_var',1,'p_dishtype_or_var','lss.py',251),
  ('sensortype_or_var -> SENSORTYPE','sensortype_or_var',1,'p_sensortype_or_var','lss.py',255),
  ('sensortype_or_var -> ID','sensortype_or_var',1,'p_sensortype_or_var','lss.py',256),
  ('instruction -> RENT EQUIPMENT COLON number_or_var COMMA hour_or_var COMMA hour_or_var COMMA date_or_var','instruction',10,'p_instruction_rent_resource','lss.py',261),
  ('instruction -> CANCEL EQUIPMENT COLON number_or_var','instruction',4,'p_instruction_cancel_resource','lss.py',278),
  ('instruction -> BUY MEAL COLON dishtype_or_var COMMA date_or_var','instruction',6,'p_instruction_buy_meal','lss.py',292),
  ('instruction -> CANCEL MEAL COLON number_or_var','instruction',4,'p_instruction_cancel_meal','lss.py',302),
  ('instruction -> REGISTER USER COLON STRING COMMA STRING COMMA NIF COMMA EMAIL COMMA ID COMMA PASSWORD COMMA USERTYPE','instruction',16,'p_instruction_register_user','lss.py',310),
  ('instruction -> REGISTER EQUIPMENT COLON ID COMMA number_or_var','instruction',6,'p_instruction_register_resource','lss.py',329),
  ('instruction -> REGISTER EQUIPMENT COLON sensortype_or_var COMMA number_or_var COMMA float_or_var','instruction',8,'p_instruction_register_sensor','lss.py',345),
  ('action -> RENT','action',1,'p_action','lss.py',356),
  ('action -> BUY','action',1,'p_action','lss.py',357),
  ('action -> REGISTER','action',1,'p_action','lss.py',358),
  ('action -> CANCEL','action',1,'p_action','lss.py',359),
]
